### ISSUE TITLE
integrate features from hopglass

### ISSUE THREAD

**Issue by maurerle** [freifunk-ffm/meshviewer#28]
Hopglass currently has features which meshviewer does not have.

* [x]  Show client count in the local mesh cloud/Anzeige der Nutzer in der lokalen Wolke #31 
* [x]  Highlight nodes with an uplink in a different color (blau) #30 
* [x]  Hardware-Images/Routerbilder #29 
* [ ]  showing Radio Channel (and Airtime) on map

To reach feature parity, we could implement these into this meshviewer, so that development does not break up into a magnitude of meshviewer projects and activly maintained repositories.

## Additional context
I am trying to push the features developed by freifunkstuff upstream.
See: https://github.com/freifunkstuff/meshviewer-ffle/issues/1

**Comment by MyIgel** [comment]
Hi @maurerle, what is the plan for this issue to go forward, does the radio channel patch already exist or is that a new one?

**Comment by maurerle** [comment]
Hi @MyIgel , the airtime is available in yanic (and on the router status page) and sent to influxdb/prometheus.
The current channel is calculated from the frequency in hopglass.

Unfortunately, such information is not available in the exported meshviewer.json created from yanic.
Probably one needs to add `Frequency11g` and `Frequency11a` here and to the Statistics struct above:
https://github.com/FreifunkBremen/yanic/blob/main/output/meshviewer/node.go#L61

The alternative is to include this in Grafana, which has access to these values and can calculate the channel from the frequency as well.
In this case, we can just close this issue as completed..?

**Comment by MyIgel** [comment]
That would be a nice feature to have but as we don't have the data directly at the moment it can be closed for now
